spring.application.name=bff-agendador-tarefas

usuario.url=${USUARIO_URL:http://localhost:8080/usuario}
agendador-tarefas.url=${TAREFAS_URL:http://localhost:8081/tarefas}
notificacao.url=${NOTIFICACAO_URL:http://localhost:8082/email}
server.port=8083
app.cors.origin=${CORS_ORIGIN:http://localhost:4200}

cron.horario=${CRON_HORARIO:0 0/1 * * * ?}

usuario.email=${CRON_USUARIO_EMAIL:}
usuario.senha=${CRON_USUARIO_SENHA:}
